name: "Netlify Production Pipeline"

on:
  push:
    branches:
      - main

jobs:
  static_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Show all Files"
        run: ls
      
      - name: "My message"
        run: echo 'Integrated Testing'
        
      - name: "run test case"
        run: exit 1
